{% set name = "pyrsm" %}
{% set version = "0.8.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrsm-{{ version }}.tar.gz
  sha256: dad631b84dc87e31a58eab0abf22a15478a4ce34257aac7dd3194ab6ec5ec7db
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - contextvars
    - mdit-py-plugins
    - shiny
    - numpy >=1.17.3
    - pandas >=0.25.2
    - seaborn >=0.9.0
    - matplotlib-base >=3.1.1
    - statsmodels >=0.10.1
    - scipy >=1.4.1
    - scikit-learn >=1.0.2
    - ipython >=8.0.1
    - nest-asyncio >=1.5.6
    - black >=22.6.0
    - xgboost >=2.0.3

test:
  imports:
    - pyrsm
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python functions for Customer Analytics at the Rady School of Management (RSM)
  dev_url: https://github.com/vnijs/pyrsm
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnijs
