{% set name = "pyrsm" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrsm-{{ version }}.tar.gz
  sha256: a50e0b12a5b96524928a28b25d953c26bd49796ec89d78d5a103e5cfd8cc653b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - numpy >=1.17.3
    - pandas >=0.25.2
    - seaborn >=0.9.0
    - matplotlib-base >=3.1.1
    - statsmodels >=0.10.1
    - scipy >=1.4.1
    - ipynbname >=2021.3.2
    - scikit-learn >=1.0.2
    - ipython >=8.0.1

test:
  imports:
    - pyrsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyrsm/
  summary: Python functions for Customer Analytics at the Rady School of Management (RSM)
  dev_url: https://github.com/vnijs/pyrsm
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnijs
